ITEM.Name = "FAMAS"
ITEM.Desc = "A bullpup-styled assault rifle that served as the service rifle of the French military. Oversized carrying handle. Chambered in 5.56x45mm NATO."
ITEM.Model = "models/weapons/tfa_ins2/w_famas.mdl"
ITEM.WeaponClass = "tfa_ins2_famas"
ITEM.Weight = 4
ITEM.SafetyPos = Vector(0,0,0)
ITEM.SafetyAng = Angle(-12.4, 0, 0)
ITEM.JamChance = 0.0002
ITEM.DegradeRate = 0.018
ITEM.FOV 			= 15
ITEM.CamPos 		= Vector( 100, 100, 0 )
ITEM.LookAt 		= Vector( 0, 0, 0 )
ITEM.SelfRepairCondition = 70
ITEM.AmmoType = "556x45"
ITEM.License = LICENSE_BLACK;
ITEM.BulkPrice = 120000
ITEM.Slot = 2
